version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: dimaska29/yamdb:latest
    restart: always
    volumes:
      - static_value:/app/api/static/
      - media_value:/app/api/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  static_value:
  media_value: